# Chapter 2: Introduction to Numpy

This notebook is a summary of code snippets within the Python Data Science Handbook. Along with some notes

In [1]:
import numpy as np

### Creating arrays from Python Lists

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Changing data type

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Multidimensional arrays with nested lists

In [4]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [5]:
# Create length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
np.random.random((3, 3))

array([[0.72862787, 0.92421196, 0.49637431],
       [0.87323658, 0.55143407, 0.67342312],
       [0.7460933 , 0.32474958, 0.21992412]])

In [11]:
# Create a 3x3 array of random integers in interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[5, 4, 8],
       [6, 4, 3],
       [8, 2, 9]])

In [12]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy Standard Data Types

| Data type | Description |
|---|---|
|bool_ | boolean (True or False) stored as a byte
|int_ | Default integer type (same as C long; normally either int64 or int32)
|intc | Identical to C int (normally int32 or int64)
|intp | Integer used for indexing (same as C size_t; normally either int32 or int64)
|int8 | Byte (-128 to 127)
|int18 | Integer (-32768 to 32767)
|int32 | Integer (-2147483648 to 2147483647)
|int64 | Integer 64bits
|uint8 | unsigned integer 8bits
|uint32 | unsigned integer 32bits
|uint64 | Unsigned integer 64bits 
|float_ | Shorthand for float64
|float16 | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa
|float32 | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa
|float64 | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa
|complex_ | Shorthand for complex128
|complex64 | Complex number, represented by two 32 bit floats
|complex128 | complex number, represented by two 64-bit floats

## The Basics of Numpy Arrays

#### NumPy Array Attributes
Setup

In [13]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

**dim, shape, size**

In [14]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


**dtype**

In [15]:
print("dtype:", x3.dtype)

dtype: int64


**itemsize, nbytes**

In [16]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


### Array Indexing, Slicing

In [17]:
x1[0]  # first item

5

In [18]:
x1[-1]  # last item

9

In [19]:
x2[0, 0]  # 1st 2-d

3

In [20]:
x2[2, -1]

7

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:5]  # First 5

array([0, 1, 2, 3, 4])

In [23]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [24]:
x[1::2]  # every other starting at index 1

array([1, 3, 5, 7, 9])

In [25]:
x[::-1]  # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x[5::-2]  # every other starting from index 5 reversed

array([5, 3, 1])

**Multidimensional Array Slicing**

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [29]:
print(x2[:, 0]) # first column

[3 7 1]


In [30]:
print(x2[0, :])  # first row
print(x2[0])  # also first row

[3 5 2 4]
[3 5 2 4]


**Subarrays as no Copy Views**

This allows for modifying sections of larger arrays without copying

In [31]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


**Creating copies of arrays**

In [35]:
x2_sub_copy = x2[:2, :2].copy()

### Reshaping Arrays

In [36]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Create a row vector**

In [37]:
x = np.array([1, 2, 3])
x.reshape(1, 3)

array([[1, 2, 3]])

In [38]:
x[np.newaxis, :]

array([[1, 2, 3]])

**create a column vector**

In [39]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [40]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

**Horizontal**

In [41]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [42]:
z = [99, 99 , 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [43]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
y = np.array([[99],
              [99]])

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

**Vertical**

In [45]:
np.concatenate(([grid, grid]))

array([[9, 8, 7],
       [6, 5, 4],
       [9, 8, 7],
       [6, 5, 4]])

In [46]:
x = np.array([1, 2, 3])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### Splitting Arrays

In [47]:
x = [1, 2, 4, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # given list of indices for split points
print(x1, x2, x3)

[1 2 4] [99 99] [3 2 1]


## Computation on NumPy Arrays: Universal Functions

***universal functions*** (ufuncs) are functions that implement ***vectorized*** operations

***Vectorized*** Operations ensure much faster calculations

### Array Arithmetic

In [48]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


**Absolute Value**

In [49]:
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [50]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)  # Returns magnitude

array([5., 5., 2., 1.])

### Trigonometric Functions

In [51]:
theta = np.linspace(0, np.pi, 3)

In [52]:
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

x = [-1, 0, 1]
print("x          =", x)
print("arcsin(x)  =", np.arcsin(x))
print("arccos(x)  =", np.arccos(x))
print("arctan(x)  =", np.arctan(x))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x          = [-1, 0, 1]
arcsin(x)  = [-1.57079633  0.          1.57079633]
arccos(x)  = [3.14159265 1.57079633 0.        ]
arctan(x)  = [-0.78539816  0.          0.78539816]


### Exponents and Logarithms

In [53]:
x = [1, 2, 3]
print("x      =", x)
print("e^x    =", np.exp(x))
print("2^x    =", np.exp2(x))
print("3^x    =", np.power(3, x))


x      = [1, 2, 3]
e^x    = [ 2.71828183  7.3890561  20.08553692]
2^x    = [2. 4. 8.]
3^x    = [ 3  9 27]
